from __future__ import annotations

from typing import Optional


# Cities and towns in Arizona (user-provided list)
ARIZONA_CITIES: list[str] = [
    "Apache Junction",
    "Avondale",
    "Benson",
    "Bisbee",
    "Buckeye",
    "Bullhead City",
    "Casa Grande",
    "Chandler",
    "Clarkdale",
    "Clifton",
    "Coolidge",
    "Cottonwood",
    "Douglas",
    "Duncan",
    "Eloy",
    "Flagstaff",
    "Florence",
    "Fountain Hills",
    "Gila Bend",
    "Gilbert",
    "Glendale",
    "Globe",
    "Goodyear",
    "Guadalupe",
    "Hayden",
    "Holbrook",
    "Jerome",
    "Kearny",
    "Kingman",
    "Lake Havasu City",
    "Litchfield Park",
    "Mammoth",
    "Marana",
    "Maricopa",
    "Mesa",
    "Miami",
    "Nogales",
    "Oro Valley",
    "Page",
    "Paradise Valley",
    "Parker",
    "Payson",
    "Peoria",
    "Phoenix",
    "Pima",
    "Pinetop–Lakeside",
    "Prescott",
    "Prescott Valley",
    "Quartzsite",
    "Queen Creek",
    "Sahuarita",
    "Safford",
    "San Luis",
    "Scottsdale",
    "Sedona",
    "Show Low",
    "Sierra Vista",
    "Snowflake",
    "Somerton",
    "South Tucson",
    "Springerville",
    "Star Valley",
    "Superior",
    "Surprise",
    "Taylor",
    "Tempe",
    "Thatcher",
    "Tolleson",
    "Tombstone",
    "Tusayan",
    "Tucson",
    "Wellton",
    "Wickenburg",
    "Willcox",
    "Williams",
    "Winkelman",
    "Winslow",
    "Youngtown",
    "Yuma",
]

_CANON = {c.casefold(): c for c in ARIZONA_CITIES}


def canonicalize_city(city: Optional[str]) -> Optional[str]:
    c = (city or "").strip()
    if not c:
        return None
    return _CANON.get(c.casefold(), c)
